### ISSUE TITLE
Enable ability to host any static assets

### ISSUE THREAD

**Issue by mudrila** [brock-boris/BIO-mechanica#3]
We're gonna add more custom styling in nearest future - thus, we surely will have some `.css` files, that we need to host.
Move through following steps, in order to enable ability to host any files on the server.

1. Create `index.css` file under `src` folder, right near to your `index.html` - https://github.com/brock-boris/BIO-mechanica/tree/main/src . Add some basic styles to your newly created `index.css` - for instance, change `body` element background color to `gray`.
2. Adjust `server.js` file - particularly you'll need to work on these lines - https://github.com/brock-boris/BIO-mechanica/blob/main/src/server.js#L7-L10 . See following StackOverflow answer for some hints on implementing proper static files serving - https://stackoverflow.com/a/29046869/8252978. Same approach discovered here - https://developer.mozilla.org/en-US/docs/Learn/Server-side/Node_server_without_framework . Note - you can use different approach, if you want.
3. Modify your `index.html` file to include your newly created `index.css`. https://www.w3schools.com/css/css_howto.asp
4. Modify `package.json` to be able to run project through `scripts`. Specifically, your script to add should be looking like `"start": "node src/server.js"`. You have to figure out how to properly add script into `package.json`. After that you should be able to run server through `yarn start`.

**Comment by brock-boris** [comment]
Finished and reviewed!
